### PR TITLE
remove xray and add code guru profiling

### PR DESCRIPTION
**Pull request by solomon-negusse**
## Pull request checklist

Please check if your PR fulfills the following requirements:
- [ ] Make sure you are requesting to pull a topic/feature/bugfix branch (right side). Don't request your master!
- [x] Make sure you are making a pull request against the develop branch (left side). Also you should start your branch off our develop.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Pull request type

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

## What is the new behavior?

This adds aws code guru profiler for method level profiling of the lambda functions

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jterry64 — APPROVED** [review]
Looks pretty sweet, it doesn't need any setup outside the code (e.g. in terraform)?

**Comment by jterry64** [comment]
I do see tests are failing due to issues with finding the right lambda layers, is there some confusion here for hotfixes @dmannarino?

**Comment by solomon-negusse** [comment]
> I do see tests are failing due to issues with finding the right lambda layers, is there some confusion here for hotfixes @dmannarino?

The tests actually pass, @jterry64  but the deployment to dev did fail. I got around this by temporarily deploying from my machine with the available layer version and assumed it's a dev only issue but would be good for @dmannarino to confirm.

**Comment by solomon-negusse** [comment]
> Looks pretty sweet, it doesn't need any setup outside the code (e.g. in terraform)?

That would be nice to add. For now, I added the code guru profiling group manually to initially see if we'll get something useful out of this.

**Comment by dmannarino** [comment]
> > I do see tests are failing due to issues with finding the right lambda layers, is there some confusion here for hotfixes @dmannarino?
> 
> The tests actually pass, @jterry64 but the deployment to dev did fail. I got around this by temporarily deploying from my machine with the available layer version and assumed it's a dev only issue but would be good for @dmannarino to help explain this.

Hmm, will look into right after lunch.

**Review by dmannarino — APPROVED** [review]

**Pull request merged**
